#! /usr/bin/env bash
set -xeuo pipefail

apk --no-cache add curl jq
curl -sSLO https://github.com/google/go-jsonnet/releases/download/v0.18.0/go-jsonnet_0.18.0_Linux_x86_64.tar.gz
echo "3b39a4e365e4a8c69064d57b23fe74368ba00ab36426b9ab1c273790b353e438  go-jsonnet_0.18.0_Linux_x86_64.tar.gz" | sha256sum -c
tar x -f go-jsonnet_0.18.0_Linux_x86_64.tar.gz -C /usr/local/bin

set +x
echo "${PRIVATE}" > vars.private.jsonnet
vars="$(jsonnet vars.jsonnet)"
set -x

jsonnet -y kubernetes/manifest.jsonnet | head -n-1 > manifest.yaml
/gke-deploy run \
  --filename manifest.yaml \
  --location "$(jq -r '.location' <<< "${vars}")" \
  --cluster "$(jq -r '.cluster.name' <<< "${vars}")"
