#! /usr/bin/env bash
set -xeuo pipefail

source .vars
manifest="$(jsonnet \
    -A project="${CLOUDSDK_CORE_PROJECT}" \
    -A location="${CLOUDSDK_COMPUTE_REGION}" \
    deployment-manager.jsonnet)"
set +x

jq . <<< "${manifest}"
read -p 'PRESS ENTER '

set -x
exec gcloud beta deployment-manager deployments update --config <(echo "${manifest}") fun-cluster
