#!/usr/bin/env bash
set -xeuo pipefail

jsonnet --tla-code-file vars=.vars deployment-manager.jsonnet | \
tee /dev/stderr | \
gcloud beta deployment-manager deployments update --config /dev/stdin fun-cluster
